/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  refresh_token_hash: string;
  revoked_at: Timestamp | null;
  user_id: string;
}

export interface AuthUsers {
  created_at: Generated<Timestamp>;
  email: string;
  full_name: string | null;
  id: Generated<string>;
  password_hash: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface GameAward {
  award_type: string;
  awarded_at: Generated<Timestamp>;
  description: string;
  game_id: Int8;
  id: Generated<string>;
  player_id: Int8;
  season_id: number;
}

export interface GameGame {
  away_score: Generated<number>;
  away_team: number;
  game_type: string;
  home_score: Generated<number>;
  home_team: number;
  id: Generated<Int8>;
  scheduled_at: Timestamp;
  scorekeeper_user_id: string | null;
  season_id: number;
  status: Int8;
  venue: string;
}

export interface GameGameEvent {
  clock_time: string;
  created_at: Generated<Timestamp>;
  event_type: string;
  event_value: number;
  game_id: Int8;
  id: Generated<Int8>;
  period: number;
  player_id: Int8;
  team_id: number;
}

export interface GameGameStats {
  assists: number;
  blocks: number;
  fgm_fga: string;
  ftm_fta: string;
  game_id: Int8;
  id: Generated<number>;
  minutes_played: number;
  personal_fouls: number;
  player_id: Int8;
  points: number;
  rebounds: number;
  steal: number;
  team_id: number;
  tpm_tpa: string;
}

export interface GameGameSummary {
  game_id: Int8;
  highlights: string;
  id: Generated<Int8>;
  narrative: string;
  published_at: Generated<Timestamp>;
}

export interface LeagueInstanceControls {
  id: string;
  maintenance_lock_enabled: Generated<boolean>;
  maintenance_lock_reason: string | null;
  maintenance_lock_updated_at: Timestamp | null;
  maintenance_lock_updated_by: string | null;
}

export interface LeagueLeague {
  contact_info: string;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<number>;
  location: string;
  logo_url: string;
  name: string;
  rules_config: Json;
}

export interface LeagueLeagueAdminInvitations {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  token_hash: string;
}

export interface LeagueLeagueInvitations {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  league_id: number;
  revoked_at: Timestamp | null;
  role: string;
  token_hash: string;
}

export interface LeagueLeagueMembers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  league_id: number;
  role: string;
  user_id: string;
}

export interface LeagueSeason {
  end_date: Timestamp;
  id: Generated<number>;
  league_id: number;
  name: string;
  playoff_format: string;
  start_date: Timestamp;
  status: Int8;
}

export interface LeagueSeasonDivision {
  age_max: number | null;
  age_min: number | null;
  archived_at: Timestamp | null;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_open: Generated<boolean>;
  name: string;
  rules_config: Generated<Json>;
  season_id: number;
  sort_order: Generated<number>;
}

export interface LeagueSeasonTeam {
  bracket: string;
  division_id: number;
  finalized_at: Timestamp | null;
  finalized_by_user_id: string | null;
  is_finalized: Generated<boolean>;
  min_required_players_snapshot: number | null;
  season_id: number;
  team_id: number;
}

export interface LeagueSeasonTeamIdentity {
  approved_at: Timestamp | null;
  approved_by_user_id: string | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  logo_url: string | null;
  primary_color: string | null;
  season_id: number;
  secondary_color: string | null;
  short_name: string | null;
  team_id: number;
  uniform_config: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface LeagueSuperAdminAuditLog {
  action_type: string;
  actor_user_id: string;
  after_snapshot: Json | null;
  before_snapshot: Json | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  reason: string | null;
  target_id: string | null;
  target_type: string;
}

export interface LeagueTeamAvailability {
  blackout_dates: Generated<Json>;
  id: Generated<Int8>;
  league_id: number;
  notes: string | null;
  season_id: number;
  team_id: number;
  updated_at: Generated<Timestamp>;
  updated_by_user_id: string | null;
}

export interface LeagueTeamComplianceItems {
  archived_at: Timestamp | null;
  category: string;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  division_id: number | null;
  id: Generated<Int8>;
  is_required: Generated<boolean>;
  key: string;
  label: string;
  league_id: number;
  season_id: number | null;
  sort_order: Generated<number>;
}

export interface LeagueTeamComplianceStatus {
  attachments: Generated<Json>;
  id: Generated<Int8>;
  item_id: Int8;
  league_id: number;
  meta: Generated<Json>;
  notes: string | null;
  season_id: number;
  status: string;
  team_id: number;
  updated_at: Generated<Timestamp>;
  updated_by_user_id: string | null;
}

export interface LeagueTeamManagerTeams {
  created_at: Generated<Timestamp>;
  league_id: number;
  team_id: number;
  user_id: string;
}

export interface LeagueTeams {
  abbreviation: string;
  coach_name: string;
  id: Generated<number>;
  league_id: number;
  logo_url: string;
  name: string;
  primary_color: string;
  secondary_color: string;
  user_id: string;
}

export interface LeagueTeamStaff {
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  email: string | null;
  full_name: string;
  id: Generated<Int8>;
  league_id: number;
  phone: string | null;
  role: string;
  season_id: number;
  team_id: number;
  updated_at: Generated<Timestamp>;
}

export interface LeagueTeamStaffRequiredRoles {
  created_at: Generated<Timestamp>;
  division_id: number | null;
  id: Generated<Int8>;
  is_required: Generated<boolean>;
  label: string;
  league_id: number;
  role: string;
  season_id: number | null;
  sort_order: Generated<number>;
}

export interface PlayerPlayer {
  date_of_birth: Timestamp;
  full_name: string;
  height_cm: number;
  id: Generated<Int8>;
  photo_url: string;
  position: string;
  weight_kg: number;
}

export interface PlayerRoster {
  id: Generated<Int8>;
  jersey_number: number;
  joined_date: Timestamp;
  player_id: Int8;
  season_id: number;
  status: string;
  team_id: number;
}

export interface DB {
  "auth.sessions": AuthSessions;
  "auth.users": AuthUsers;
  "game.Award": GameAward;
  "game.Game": GameGame;
  "game.GameEvent": GameGameEvent;
  "game.GameStats": GameGameStats;
  "game.GameSummary": GameGameSummary;
  "league.instance_controls": LeagueInstanceControls;
  "league.League": LeagueLeague;
  "league.league_admin_invitations": LeagueLeagueAdminInvitations;
  "league.league_invitations": LeagueLeagueInvitations;
  "league.league_members": LeagueLeagueMembers;
  "league.Season": LeagueSeason;
  "league.season_team_identity": LeagueSeasonTeamIdentity;
  "league.SeasonDivision": LeagueSeasonDivision;
  "league.SeasonTeam": LeagueSeasonTeam;
  "league.super_admin_audit_log": LeagueSuperAdminAuditLog;
  "league.team_availability": LeagueTeamAvailability;
  "league.team_compliance_items": LeagueTeamComplianceItems;
  "league.team_compliance_status": LeagueTeamComplianceStatus;
  "league.team_manager_teams": LeagueTeamManagerTeams;
  "league.team_staff": LeagueTeamStaff;
  "league.team_staff_required_roles": LeagueTeamStaffRequiredRoles;
  "league.Teams": LeagueTeams;
  "player.Player": PlayerPlayer;
  "player.Roster": PlayerRoster;
}
